# Generated by Django 5.1.3 on 2024-11-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_post_author_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.TextField(max_length=250),
        ),
    ]
